[workspace.package]
name = "RustyGw2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
	"Overlay",
	"gw2_link",
	"custom_window_plugin"
]
